#!/bin/bash
# Скрипт для автоматичного налаштування DNS в Cloudflare
# Використання: Зайдіть в Cloudflare Dashboard і виконайте ці дії вручну

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      НАЛАШТУВАННЯ DNS В CLOUDFLARE                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Зайдіть: https://dash.cloudflare.com"
echo "2. Виберіть домен: repairhub.com"
echo "3. Перейдіть до: DNS → Records"
echo "4. Натисніть 'Add record' (два рази)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ЗАПИС 1:"
echo "═══════════════════════════════════════════════════════════════"
echo "Type: A"
echo "Name: @"
echo "Content: 70.34.252.148"
echo "Proxy status: DNS only (СІРА хмара!)"
echo "TTL: Auto"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ЗАПИС 2:"
echo "═══════════════════════════════════════════════════════════════"
echo "Type: A"
echo "Name: www"
echo "Content: 70.34.252.148"
echo "Proxy status: DNS only (СІРА хмара!)"
echo "TTL: Auto"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ПОСЛЯ ДОДАВАННЯ RECORDS:"
echo "═══════════════════════════════════════════════════════════════"
echo "Виконайте на сервері:"
echo ""
echo "ssh root@70.34.252.148"
echo "cd /root/repair-hub-pro"
echo "nano nginx.conf"
echo "# Змініть: listen 3000; → listen 80;"
echo "docker compose down"
echo "docker compose build --no-cache"
echo "docker compose up -d"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Чекайте 5-30 хвилин і відкрийте:"
echo "http://repairhub.com"
echo "═══════════════════════════════════════════════════════════════"

