services:
  repair-hub-pro:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"   # HTTP port
    environment:
      - NODE_ENV=production
    restart: always
    container_name: repair-hub-pro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - repair-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - nginx-logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "production"

volumes:
  nginx-logs:
    driver: local
  app-data:
    driver: local

networks:
  repair-network:
    driver: bridge

