export const portfolioItems = [
  {
    id: 1,
    title: 'Заміна екрану iPhone 15 Pro Max',
    description: 'Повна заміна дисплея з оригінальними запчастинами Apple',
    beforeImage: '/images/portfolio/placeholder-before.svg',
    afterImage: '/images/portfolio/placeholder-after.svg',
    price: 8500,
    completedAt: '2024-10-15',
    deviceType: 'iPhone',
    issue: 'Пошкодження екрану',
  },
  {
    id: 2,
    title: 'Ремонт логічної плати MacBook Air M2',
    description: 'Діагностика та ремонт материнської плати після заливання водою',
    beforeImage: '/images/portfolio/placeholder-before.svg',
    afterImage: '/images/portfolio/placeholder-after.svg',
    price: 12000,
    completedAt: '2024-10-10',
    deviceType: 'Mac',
    issue: 'Пошкодження від рідини',
  },
  {
    id: 3,
    title: 'Заміна батареї iPad Pro 12.9"',
    description: 'Заміна акумулятора з гарантією на 6 місяців',
    beforeImage: 'https://via.placeholder.com/300x200/FF6B6B/FFFFFF?text=Стара+батарея',
    afterImage: 'https://via.placeholder.com/300x200/4ECDC4/FFFFFF?text=Нова+батарея',
    price: 4500,
    completedAt: '2024-10-05',
    deviceType: 'iPad',
    issue: 'Проблема з батареєю',
  },
  {
    id: 4,
    title: 'Ремонт камери iPhone 14 Pro',
    description: 'Заміна задньої камери з калібруванням',
    beforeImage: 'https://via.placeholder.com/300x200/FF6B6B/FFFFFF?text=Несправна+камера',
    afterImage: 'https://via.placeholder.com/300x200/4ECDC4/FFFFFF?text=Нова+камера',
    price: 3200,
    completedAt: '2024-09-28',
    deviceType: 'iPhone',
    issue: 'Несправність обладнання',
  },
  {
    id: 5,
    title: 'Заміна дисплея Apple Watch Series 8',
    description: 'Ремонт екрану з підтримкою Always-On Display',
    beforeImage: 'https://via.placeholder.com/300x200/FF6B6B/FFFFFF?text=Розбитий+екран',
    afterImage: 'https://via.placeholder.com/300x200/4ECDC4/FFFFFF?text=Новий+екран',
    price: 2800,
    completedAt: '2024-09-20',
    deviceType: 'Apple Watch',
    issue: 'Пошкодження екрану',
  },
  {
    id: 6,
    title: 'Ремонт клавіатури MacBook Pro 16"',
    description: 'Заміна клавіатури з підтримкою Touch Bar',
    beforeImage: 'https://via.placeholder.com/300x200/FF6B6B/FFFFFF?text=Пошкоджена+клавіатура',
    afterImage: 'https://via.placeholder.com/300x200/4ECDC4/FFFFFF?text=Нова+клавіатура',
    price: 6500,
    completedAt: '2024-09-15',
    deviceType: 'Mac',
    issue: 'Несправність обладнання',
  },
];
