import { User, Order, PortfolioItem, Proposal, Message, ProgressUpdate, FreelanceProposal } from '../types/models';
import { APPLE_MODELS, CATEGORIES, YEARS } from './appleModels';
import { UKRAINIAN_CITIES, REGIONS } from './ukrainianCities';

// Валюти
export const CURRENCIES = [
  { code: 'UAH', symbol: '₴', name: 'Українська гривня', label: 'ГРН' },
  { code: 'USD', symbol: '$', name: 'Американський долар', label: 'USD' },
  { code: 'USDT', symbol: '₮', name: 'Tether (USDT)', label: 'USDT' }
];

export const DEFAULT_CURRENCY = 'UAH';

// ===== ОСНОВНЫЕ ПОЛЬЗОВАТЕЛИ =====
export const mockUsers: User[] = [
  // КЛИЕНТЫ
  {
    id: 'client1',
    name: 'Анна Коваленко',
    fullName: 'Анна Коваленко',
    role: 'client',
    avatar: 'https://i.pravatar.cc/96?img=1',
    rating: 4.8,
    email: 'anna.kovalenko@gmail.com',
    password: 'password123',
    phone: '+380501234567',
    verified: true,
    city: 'Київ',
    balance: 15000,
    skills: [],
    specialization: 'Client',
    paymentMethods: [
      {
        id: '1',
        type: 'card',
        name: 'Visa **** 1234',
        last4: '1234',
        isDefault: true,
        isActive: true
      },
      {
        id: '2',
        type: 'bank',
        name: 'Монобанк',
        isDefault: false,
        isActive: true
      }
    ]
  },
  {
    id: 'client2',
    name: 'Михайло Петренко',
    fullName: 'Михайло Петренко',
    role: 'client',
    avatar: 'https://i.pravatar.cc/96?img=2',
    rating: 4.9,
    email: 'm.petrenko@ukr.net',
    password: 'password123',
    phone: '+380671234567',
    verified: true,
    city: 'Харків',
    skills: [],
    specialization: 'Client',
    balance: 10000
  },
  {
    id: 'client3',
    name: 'Олена Сидоренко',
    fullName: 'Олена Сидоренко',
    role: 'client',
    avatar: 'https://i.pravatar.cc/96?img=3',
    rating: 4.7,
    email: 'elena.sidorenko@gmail.com',
    password: 'password123',
    phone: '+380631234567',
    verified: true,
    city: 'Львів',
    skills: [],
    specialization: 'Client',
    balance: 5000
  },
  
  // МАСТЕРИ
  {
    id: 'master1',
    name: 'Олександр Петренко',
    fullName: 'Олександр Петренко',
    role: 'master',
    avatar: 'https://i.pravatar.cc/96?img=4',
    rating: 4.9,
    email: 'alex.petrenko@repair.ua',
    password: 'password123',
    phone: '+380501234567',
    verified: true,
    city: 'Київ',
    skills: ['iPhone', 'iPad', 'MacBook'],
    specialization: 'Екрани iPhone',
    experience: '5 років',
    completedOrders: 1247,
    balance: 25000
  },
  {
    id: 'master2',
    name: 'Марія Коваленко',
    fullName: 'Марія Коваленко',
    role: 'master',
    avatar: 'https://i.pravatar.cc/96?img=5',
    rating: 4.8,
    email: 'maria.kovalenko@repair.ua',
    password: 'password123',
    phone: '+380501234568',
    verified: true,
    city: 'Харків',
    skills: ['iPhone', 'iPad'],
    specialization: 'Заміна батарей',
    experience: '4 роки',
    completedOrders: 956,
    balance: 15000
  },
  {
    id: 'master3',
    name: 'Ігор Мельник',
    fullName: 'Ігор Мельник',
    role: 'master',
    avatar: 'https://i.pravatar.cc/96?img=6',
    rating: 4.95,
    email: 'igor.melnyk@repair.ua',
    password: 'password123',
    phone: '+380501234569',
    verified: true,
    city: 'Харків',
    skills: ['MacBook', 'iPhone'],
    specialization: 'Експертний ремонт',
    experience: '7 років',
    completedOrders: 1843,
    balance: 35000
  },
  {
    id: 'master4',
    name: 'Тарас Бандера',
    fullName: 'Тарас Бандера',
    role: 'master',
    avatar: 'https://i.pravatar.cc/96?img=7',
    rating: 4.85,
    email: 'taras.bandera@repair.ua',
    password: 'password123',
    phone: '+380501234570',
    verified: true,
    city: 'Львів',
    skills: ['iPhone', 'iPad'],
    specialization: 'Мобільний ремонт',
    experience: '3 роки',
    completedOrders: 723,
    balance: 10000
  },
  {
    id: 'master5',
    name: 'Оксана Петренко',
    fullName: 'Оксана Петренко',
    role: 'master',
    avatar: 'https://i.pravatar.cc/96?img=8',
    rating: 4.9,
    email: 'oksana.petrenko@repair.ua',
    password: 'password123',
    phone: '+380501234571',
    verified: true,
    city: 'Львів',
    skills: ['iPhone', 'MacBook'],
    specialization: 'Професійний сервіс',
    experience: '6 років',
    completedOrders: 1156,
    balance: 20000
  },
  {
    id: 'master6',
    name: 'Андрій Павленко',
    fullName: 'Андрій Павленко',
    role: 'master',
    avatar: 'https://i.pravatar.cc/96?img=9',
    rating: 4.75,
    email: 'andriy.pavlenko@repair.ua',
    password: 'password123',
    phone: '+380501234572',
    verified: true,
    city: 'Одеса',
    skills: ['iPad', 'MacBook'],
    specialization: 'Професійний ремонт',
    experience: '4 роки',
    completedOrders: 892,
    balance: 12000
  },
  // АДМІНІСТРАТОР
  {
    id: 'admin1',
    name: 'Адміністратор',
    fullName: 'Адміністратор Системи',
    role: 'admin',
    avatar: 'https://i.pravatar.cc/96?img=10',
    rating: 5.0,
    email: 'admin@repairhub.pro',
    password: 'password123',
    phone: '+380991234567',
    verified: true,
    city: 'Платформа',
    skills: ['all'],
    specialization: 'Системне адміністрування',
    balance: 0
  },
];

// ===== ЗАКАЗЫ =====
export const mockOrders: Order[] = [
  {
    id: 'order1',
    title: 'Ремонт екрану iPhone 15 Pro',
    deviceType: 'iPhone',
    device: 'iPhone 15 Pro',
    city: 'Київ',
    budget: 8500,
    proposalCount: 1,
    brand: 'Apple',
    issue: 'Пошкодження екрану',
    description: 'Розбитий екран після падіння. Потрібна заміна дисплею.',
    status: 'open',
    urgency: 'high',
    clientId: 'client1',
    clientName: 'Анна Коваленко',
    masterId: undefined,
    proposedPrice: 8500,
    agreedPrice: undefined,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
    location: 'Київ, вул. Хрещатик, 22',
    clientPhone: '+380501234567',
    clientEmail: 'anna.kovalenko@gmail.com',
    paymentStatus: 'pending',
    paymentAmount: 8500,
    paymentMethod: 'Visa **** 1234',
    escrowId: 'escrow_001',
    paymentDate: new Date('2025-01-19'),
    disputeStatus: 'none',
  },
  {
    id: 'order2',
    title: 'Заміна батареї iPhone 14',
    deviceType: 'iPhone',
    device: 'iPhone 14',
    city: 'Харків',
    budget: 3200,
    proposalCount: 1,
    issue: 'Проблема з батареєю',
    description: 'Батарея швидко розряджається. Потрібна заміна.',
    status: 'accepted',
    urgency: 'medium',
    clientId: 'client2',
    clientName: 'Михайло Петренко',
    masterId: 'master2',
    proposedPrice: 3200,
    agreedPrice: 3000,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-19'),
    location: 'Харків, вул. Сумська, 15',
    clientPhone: '+380671234567',
    clientEmail: 'm.petrenko@ukr.net',
    paymentStatus: 'escrowed',
    paymentAmount: 3000,
    paymentMethod: 'Монобанк',
    escrowId: 'escrow_002',
    paymentDate: new Date('2025-01-18'),
    disputeStatus: 'open',
    disputeReason: 'Якість роботи',
    disputeCreatedAt: new Date('2025-01-19'),
    supportTicketId: 'TICKET-001'
  },
  {
    id: 'order3',
    title: 'Ремонт MacBook Pro 16"',
    deviceType: 'Mac',
    device: 'MacBook Pro 16"',
    city: 'Львів',
    budget: 15000,
    proposalCount: 1,
    issue: 'Несправність обладнання',
    description: 'MacBook не включається. Потрібна діагностика.',
    status: 'in_progress',
    urgency: 'high',
    clientId: 'client3',
    masterId: 'master3',
    proposedPrice: 15000,
    agreedPrice: 14000,
    createdAt: new Date('2025-01-17'),
    updatedAt: new Date('2025-01-19'),
    location: 'Львів, вул. Городоцька, 8',
    clientPhone: '+380631234567',
    clientEmail: 'elena.sidorenko@gmail.com',
    paymentStatus: 'escrowed',
    paymentAmount: 14000,
    paymentMethod: 'USDT (TRC20)',
    escrowId: 'escrow_003',
    paymentDate: new Date('2025-01-17'),
    clientName: 'Олена Сидоренко',
    disputeStatus: 'none',
  },
  {
    id: 'order4',
    title: 'Заміна дисплею iPad Air',
    deviceType: 'iPad',
    device: 'iPad Air',
    city: 'Київ',
    budget: 6500,
    proposalCount: 1,
    issue: 'Пошкодження екрану',
    description: 'Тріщина на екрані iPad Air. Потрібна заміна дисплею.',
    status: 'completed',
    urgency: 'low',
    clientId: 'client1',
    masterId: 'master4',
    proposedPrice: 6500,
    agreedPrice: 6000,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-18'),
    location: 'Київ, вул. Хрещатик, 22',
    clientPhone: '+380501234567',
    clientEmail: 'anna.kovalenko@gmail.com',
    paymentStatus: 'released',
    paymentAmount: 6000,
    paymentMethod: 'Visa **** 1234',
    escrowId: 'escrow_004',
    paymentDate: new Date('2025-01-15'),
    releaseDate: new Date('2025-01-16'),
    clientName: 'Анна Коваленко',
    disputeStatus: 'none',
  },
  {
    id: 'order5',
    title: 'Чистка від вологи iPhone 13',
    deviceType: 'iPhone',
    device: 'iPhone 13',
    city: 'Харків',
    budget: 4500,
    proposalCount: 0,
    issue: 'Пошкодження від рідини',
    description: 'iPhone попав в воду. Потрібна професійна чистка.',
    status: 'open',
    urgency: 'high',
    clientId: 'client2',
    clientName: 'Михайло Петренко',
    masterId: undefined,
    proposedPrice: 4500,
    agreedPrice: undefined,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
    location: 'Харків, вул. Сумська, 15',
    clientPhone: '+380671234567',
    clientEmail: 'm.petrenko@ukr.net',
    paymentStatus: 'pending',
    paymentAmount: 4500,
    paymentMethod: 'Монобанк',
    escrowId: 'escrow_005',
    paymentDate: new Date('2025-01-19'),
    disputeStatus: 'none',
  },
  // Заказы для демо пользователей с ID типа client-1, master-1
  {
    id: 'order-demo-1',
    title: 'Ремонт стиральної машини',
    deviceType: 'washer',
    device: 'Whirlpool',
    city: 'Москва',
    budget: 3500,
    proposalCount: 2,
    issue: 'Не греває воду',
    description: 'Стиральна машина не підігріває воду. Потрібна діагностика та ремонт.',
    status: 'in_progress',
    urgency: 'medium',
    clientId: 'client-1',
    clientName: 'Владимир Петров',
    masterId: 'master-1',
    masterName: 'Олександр Петренко',
    proposedPrice: 3500,
    agreedPrice: 3500,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-19'),
    location: 'Москва, вул. Тверська, 10',
    clientPhone: '+79991234567',
    clientEmail: 'client@example.com',
    paymentStatus: 'escrowed',
    paymentAmount: 3500,
    paymentMethod: 'Visa',
    escrowId: 'escrow_demo_1',
    paymentDate: new Date('2025-01-15'),
    disputeStatus: 'none',
  },
  {
    id: 'order-demo-2',
    title: 'Установка кондиціонера',
    deviceType: 'air-conditioner',
    device: 'LG',
    city: 'Москва',
    budget: 8500,
    proposalCount: 1,
    issue: 'Встановлення нового кондиціонера',
    description: 'Потрібно встановити новий кондиціонер в спальні.',
    status: 'in_progress',
    urgency: 'low',
    clientId: 'client-1',
    clientName: 'Владимир Петров',
    masterId: 'master-1',
    masterName: 'Олександр Петренко',
    proposedPrice: 8500,
    agreedPrice: 8500,
    createdAt: new Date('2025-01-16'),
    updatedAt: new Date('2025-01-19'),
    location: 'Москва, вул. Леніна, 15',
    clientPhone: '+79991234567',
    clientEmail: 'client@example.com',
    paymentStatus: 'escrowed',
    paymentAmount: 8500,
    paymentMethod: 'Visa',
    escrowId: 'escrow_demo_2',
    paymentDate: new Date('2025-01-16'),
    disputeStatus: 'none',
  },
  {
    id: 'order-demo-3',
    title: 'Ремонт холодильника',
    deviceType: 'refrigerator',
    device: 'Samsung',
    city: 'Москва',
    budget: 4200,
    proposalCount: 0,
    issue: 'Холодильник не охолоджує',
    description: 'Холодильник перестав охолоджувати продукти. Потрібна негайна діагностика.',
    status: 'open',
    urgency: 'high',
    clientId: 'client-1',
    clientName: 'Владимир Петров',
    masterId: undefined,
    proposedPrice: 4200,
    agreedPrice: undefined,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
    location: 'Москва, вул. Красна, 25',
    clientPhone: '+79991234567',
    clientEmail: 'client@example.com',
    paymentStatus: 'pending',
    paymentAmount: 4200,
    paymentMethod: 'Visa',
    escrowId: 'escrow_demo_3',
    paymentDate: new Date('2025-01-19'),
    disputeStatus: 'none',
  },
  {
    id: 'order-demo-4',
    title: 'Чистка посудомийної машини',
    deviceType: 'dishwasher',
    device: 'Bosch',
    city: 'Москва',
    budget: 2500,
    proposalCount: 3,
    issue: 'Погане очищення посуду',
    description: 'Посудомийна машина погано миє посуд. Потрібна чистка та технічне обслуговування.',
    status: 'completed',
    urgency: 'low',
    clientId: 'client-1',
    clientName: 'Владимир Петров',
    masterId: 'master-1',
    masterName: 'Олександр Петренко',
    proposedPrice: 2500,
    agreedPrice: 2500,
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-18'),
    location: 'Москва, пр. Мира, 5',
    clientPhone: '+79991234567',
    clientEmail: 'client@example.com',
    paymentStatus: 'released',
    paymentAmount: 2500,
    paymentMethod: 'Visa',
    escrowId: 'escrow_demo_4',
    paymentDate: new Date('2025-01-10'),
    releaseDate: new Date('2025-01-18'),
    disputeStatus: 'none',
  }
];

// ===== ПОРТФОЛИО МАСТЕРОВ =====
export const mockPortfolio: PortfolioItem[] = [
  {
    id: 'portfolio1',
    masterId: 'master1',
    title: 'Заміна екрану iPhone 15 Pro',
    description: 'Професійна заміна дисплею iPhone 15 Pro з оригінальними запчастинами',
    photos: ['https://via.placeholder.com/300x200?text=До+ремонту', 'https://via.placeholder.com/300x200?text=Після+ремонту'],
    images: ['https://via.placeholder.com/300x200?text=До+ремонту', 'https://via.placeholder.com/300x200?text=Після+ремонту'],
    price: 8500,
    completedDate: new Date('2025-01-15'),
    rating: 5,
    clientReview: 'Відмінна робота! Екран як новий.',
    deviceType: 'iPhone',
    issue: 'Пошкодження екрану'
  },
  {
    id: 'portfolio2',
    masterId: 'master2',
    title: 'Заміна батареї iPhone 14',
    description: 'Швидка заміна батареї iPhone 14 з гарантією',
    photos: ['https://via.placeholder.com/300x200?text=Стара+батарея', 'https://via.placeholder.com/300x200?text=Нова+батарея'],
    images: ['https://via.placeholder.com/300x200?text=Стара+батарея', 'https://via.placeholder.com/300x200?text=Нова+батарея'],
    price: 3200,
    completedDate: new Date('2025-01-12'),
    rating: 5,
    clientReview: 'Батарея тепер тримає набагато довше!',
    deviceType: 'iPhone',
    issue: 'Проблема з батареєю'
  },
  {
    id: 'portfolio3',
    masterId: 'master3',
    title: 'Ремонт MacBook Pro 16"',
    description: 'Складний ремонт материнської плати MacBook Pro',
    photos: ['https://via.placeholder.com/300x200?text=Не+працює', 'https://via.placeholder.com/300x200?text=Працює+ідеально'],
    images: ['https://via.placeholder.com/300x200?text=Не+працює', 'https://via.placeholder.com/300x200?text=Працює+ідеально'],
    price: 15000,
    completedDate: new Date('2025-01-10'),
    rating: 5,
    clientReview: 'Майстер врятував мій MacBook!',
    deviceType: 'Mac',
    issue: 'Несправність обладнання'
  }
];

// ===== ПРЕДЛОЖЕНИЯ =====
export const mockProposals: Proposal[] = [
  {
    id: 'proposal1',
    orderId: 'order1',
    masterId: 'master1',
    price: 8500,
    description: 'Заміна екрану iPhone 15 Pro з оригінальними запчастинами. Гарантія 6 місяців.',
    estimatedTime: '2-3 години',
    status: 'pending',
    createdAt: new Date('2025-01-19'),
    masterName: 'Олександр Петренко',
    masterRating: 4.9,
    estimatedDays: 1,
    masterAvatar: 'https://i.pravatar.cc/96?img=4'
  },
  {
    id: 'proposal2',
    orderId: 'order2',
    masterId: 'master2',
    price: 3000,
    description: 'Заміна батареї iPhone 14. Оригінальна батарея, гарантія 1 рік.',
    estimatedTime: '1 година',
    status: 'accepted',
    createdAt: new Date('2025-01-18'),
    masterName: 'Марія Коваленко',
    masterRating: 4.8,
    estimatedDays: 1,
    masterAvatar: 'https://i.pravatar.cc/96?img=5'
  },
  {
    id: 'proposal3',
    orderId: 'order1',
    masterId: 'master1',
    price: 8500,
    description: 'Заміна екрану iPhone 15 Pro з оригінальними запчастинами. Гарантія 6 місяців.',
    estimatedTime: '2-3 години',
    status: 'accepted',
    createdAt: new Date('2025-01-19'),
    masterName: 'Олександр Петренко',
    masterRating: 4.9,
    estimatedDays: 1,
    masterAvatar: 'https://i.pravatar.cc/96?img=4'
  }
];

// ===== СООБЩЕНИЯ =====
export const mockMessages: Message[] = [
  {
    id: 'msg1',
    senderId: 'client1',
    recipientId: 'master1',
    text: 'Привіт! Можеш сьогодні переглянути мій iPhone?',
    timestamp: new Date('2025-01-19T10:15:00'),
    read: true
  },
  {
    id: 'msg2',
    senderId: 'master1',
    recipientId: 'client1',
    text: 'Привіт! Так, звісно можу. Можу почати завтра о 10:00',
    timestamp: new Date('2025-01-19T10:30:00'),
    read: true
  },
  {
    id: 'msg3',
    senderId: 'client2',
    recipientId: 'master2',
    text: 'Спасибо за ремонт! Батарея теперь работает отлично.',
    timestamp: new Date('2025-01-19T16:11:00'),
    read: true
  }
];

// ===== ОБНОВЛЕНИЯ ПРОГРЕССА =====
export const mockProgressUpdates: ProgressUpdate[] = [
  {
    id: 'update1',
    orderId: 'order3',
    masterId: 'master3',
    status: 'in_progress',
    description: 'Почав діагностику MacBook. Перевіряю материнську плату.',
    createdAt: new Date('2025-01-19T14:30:00'),
    photos: ['https://via.placeholder.com/300x200?text=Діагностика']
  },
  {
    id: 'update2',
    orderId: 'order3',
    masterId: 'master3',
    status: 'in_progress',
    description: 'Знайшов проблему - пошкоджений конектор. Замінюю деталь.',
    createdAt: new Date('2025-01-19T15:45:00'),
    photos: ['https://via.placeholder.com/300x200?text=Заміна+конектора']
  }
];

// ===== ФРИЛАНС ПРЕДЛОЖЕНИЯ =====
export const mockFreelanceProposals: FreelanceProposal[] = [
  {
    id: 'freelance1',
    title: 'Ремонт iPhone 15 Pro Max',
    description: 'Потрібен майстер для ремонту екрану iPhone 15 Pro Max в Києві',
    clientId: 'client1',
    budget: 10000,
    deadline: new Date('2025-01-25'),
    status: 'open',
    skills: ['iPhone', 'Screen Repair'],
    location: 'Київ',
    createdAt: new Date('2025-01-19'),
    clientName: 'Анна Коваленко',
    clientRating: 4.8
  },
  // Новые заказы с разными брендами
  {
    id: 'order6',
    title: 'Ремонт екрану Xiaomi Mi 14',
    deviceType: 'Other',
    brand: 'Xiaomi',
    issue: 'Пошкодження екрану',
    description: 'Розбитий екран Xiaomi Mi 14. Потрібна заміна дисплею.',
    status: 'open',
    urgency: 'high',
    clientId: 'client2',
    masterId: '',
    proposedPrice: 4500,
    agreedPrice: 0,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
    location: 'Харків, вул. Сумська, 15',
    clientPhone: '+380501234568',
    clientEmail: 'maria.petrenko@gmail.com',
    paymentStatus: 'pending',
    paymentAmount: 4500,
    paymentMethod: 'Mastercard **** 5678',
    escrowId: 'escrow_006',
    clientName: 'Марія Петренко',
    clientRating: 4.9,
    budget: 4500,
    deadline: new Date('2025-01-25')
  },
  {
    id: 'order7',
    title: 'Заміна батареї Huawei P60',
    deviceType: 'Other',
    brand: 'Huawei',
    issue: 'Проблема з батареєю',
    description: 'Батарея Huawei P60 не тримає заряд. Потрібна заміна.',
    status: 'open',
    urgency: 'medium',
    clientId: 'client3',
    masterId: '',
    proposedPrice: 2800,
    agreedPrice: 0,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-18'),
    location: 'Львів, вул. Городоцька, 8',
    clientPhone: '+380501234569',
    clientEmail: 'andriy.shevchenko@gmail.com',
    paymentStatus: 'pending',
    paymentAmount: 2800,
    paymentMethod: 'Visa **** 9012',
    escrowId: 'escrow_007',
    clientName: 'Андрій Шевченко',
    clientRating: 4.7,
    budget: 2800,
    deadline: new Date('2025-01-25')
  },
  {
    id: 'order8',
    title: 'Ремонт OnePlus 12 - заміна камери',
    deviceType: 'Other',
    brand: 'OnePlus',
    issue: 'Несправність обладнання',
    description: 'Камера OnePlus 12 не фокусується. Потрібна заміна модуля камери.',
    status: 'open',
    urgency: 'low',
    clientId: 'client4',
    masterId: 'master2',
    proposedPrice: 3500,
    agreedPrice: 0,
    createdAt: new Date('2025-01-17'),
    updatedAt: new Date('2025-01-17'),
    location: 'Одеса, вул. Дерибасівська, 12',
    clientPhone: '+380501234570',
    clientEmail: 'viktor.morozenko@gmail.com',
    paymentStatus: 'pending',
    paymentAmount: 3500,
    paymentMethod: 'Mastercard **** 3456',
    escrowId: 'escrow_008',
    clientName: 'Віктор Морозенко',
    clientRating: 4.8,
    budget: 3500,
    deadline: new Date('2025-01-25')
  },
  {
    id: 'order9',
    title: 'Чистка від вологи Google Pixel 8',
    deviceType: 'Other',
    brand: 'Google',
    issue: 'Пошкодження від рідини',
    description: 'Google Pixel 8 потрапив під дощ. Потрібна професійна чистка.',
    status: 'open',
    urgency: 'high',
    clientId: 'client5',
    masterId: '',
    proposedPrice: 4000,
    agreedPrice: 0,
    createdAt: new Date('2025-01-16'),
    updatedAt: new Date('2025-01-16'),
    location: 'Дніпро, вул. Набережна, 25',
    clientPhone: '+380501234571',
    clientEmail: 'natalia.kozlova@gmail.com',
    paymentStatus: 'pending',
    paymentAmount: 4000,
    paymentMethod: 'Visa **** 7890',
    escrowId: 'escrow_009',
    clientName: 'Наталія Козлова',
    clientRating: 4.6,
    budget: 4000,
    deadline: new Date('2025-01-25')
  }
];

// ===== ЗАКАЗЫ ДЛЯ МАСТЕРОВ (СЕРВИС НАЗНАЧАЕТ) =====
export const mockMasterOrders: Order[] = [
  {
    id: 'master_order1',
    title: 'Ремонт iPhone 15 Pro - заміна екрану',
    deviceType: 'iPhone',
    device: 'iPhone 15 Pro',
    city: 'Київ',
    budget: 8500,
    proposalCount: 1,
    issue: 'Пошкодження екрану',
    description: 'Клієнт звернувся до сервісу. Потрібна заміна екрану iPhone 15 Pro з оригінальними запчастинами.',
    status: 'in_progress',
    urgency: 'high',
    clientId: 'service1',
    masterId: 'master1',
    proposedPrice: 8500,
    agreedPrice: 8000,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-19'),
    location: 'Київ, вул. Хрещатик, 22',
    clientPhone: '+380501234567',
    clientEmail: 'service@repairhub.pro',
    paymentStatus: 'pending',
    paymentAmount: 8000,
    paymentMethod: 'Service Account',
    escrowId: 'escrow_master_001',
    assignedBy: 'service1',
    assignedAt: new Date('2025-01-19'),
    deadline: new Date('2025-01-22'),
    priority: 'high',
    notes: 'Клієнт очікує швидкого ремонту. Запчастини в наявності.',
    clientName: 'Олексій Коваленко',
    clientRating: 4.8,
    paymentDate: new Date('2025-01-19'),
    disputeStatus: 'none',
  },
  {
    id: 'master_order2',
    title: 'Заміна батареї MacBook Pro 16"',
    deviceType: 'Mac',
    device: 'MacBook Pro 16"',
    city: 'Харків',
    budget: 4500,
    proposalCount: 1,
    issue: 'Проблема з батареєю',
    description: 'MacBook Pro 16" не тримає заряд. Потрібна заміна батареї з калібруванням.',
    status: 'in_progress',
    urgency: 'medium',
    clientId: 'service1',
    masterId: 'master2',
    proposedPrice: 4500,
    agreedPrice: 4200,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-01-19'),
    location: 'Харків, вул. Сумська, 15',
    clientPhone: '+380501234568',
    clientEmail: 'service@repairhub.pro',
    paymentStatus: 'pending',
    paymentAmount: 4200,
    paymentMethod: 'Service Account',
    escrowId: 'escrow_master_002',
    assignedBy: 'service1',
    assignedAt: new Date('2025-01-18'),
    deadline: new Date('2025-01-21'),
    priority: 'medium',
    notes: 'Батарея вже замовлена. Очікуємо доставку.',
    clientName: 'Марія Петренко',
    clientRating: 4.9,
    paymentDate: new Date('2025-01-18'),
    disputeStatus: 'none',
  },
  {
    id: 'master_order3',
    title: 'Ремонт iPad Air - заміна дисплею',
    deviceType: 'iPad',
    device: 'iPad Air',
    city: 'Львів',
    budget: 3200,
    proposalCount: 0,
    issue: 'Пошкодження екрану',
    description: 'iPad Air отримав механічні пошкодження екрану. Потрібна заміна дисплею.',
    status: 'open',
    urgency: 'low',
    clientId: 'service1',
    masterId: null,
    proposedPrice: 3200,
    agreedPrice: 0,
    createdAt: new Date('2025-01-17'),
    updatedAt: new Date('2025-01-17'),
    location: 'Львів, вул. Городоцька, 8',
    clientPhone: '+380501234569',
    clientEmail: 'service@repairhub.pro',
    paymentStatus: 'pending',
    paymentAmount: 3200,
    paymentMethod: 'Service Account',
    escrowId: 'escrow_master_003',
    assignedBy: 'service1',
    assignedAt: null,
    deadline: new Date('2025-01-25'),
    priority: 'low',
    notes: 'Потрібно знайти майстра у Львові. Запчастини є в наявності.',
    clientName: 'Оксана Іваненко',
    clientRating: 4.7,
    paymentDate: new Date('2025-01-17'),
    disputeStatus: 'none',
  },
  {
    id: 'master_order4',
    title: 'Чистка від вологи iPhone 13 Pro',
    deviceType: 'iPhone',
    device: 'iPhone 13 Pro',
    city: 'Одеса',
    budget: 2800,
    proposalCount: 1,
    issue: 'Пошкодження від рідини',
    description: 'iPhone 13 Pro потрапив під дощ. Потрібна професійна чистка від вологи.',
    status: 'completed',
    urgency: 'high',
    clientId: 'service1',
    masterId: 'master3',
    proposedPrice: 2800,
    agreedPrice: 2500,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-16'),
    location: 'Одеса, вул. Дерибасівська, 12',
    clientPhone: '+380501234570',
    clientEmail: 'service@repairhub.pro',
    paymentStatus: 'released',
    paymentAmount: 2500,
    paymentMethod: 'Service Account',
    escrowId: 'escrow_master_004',
    assignedBy: 'service1',
    assignedAt: new Date('2025-01-15'),
    deadline: new Date('2025-01-18'),
    priority: 'high',
    notes: 'Ремонт завершено успішно. Клієнт задоволений.',
    clientName: 'Віктор Морозенко',
    clientRating: 4.8,
    paymentDate: new Date('2025-01-15'),
    disputeStatus: 'none',
  }
];

// ===== ЭКСПОРТ ДАННЫХ =====
export { APPLE_MODELS, CATEGORIES, YEARS, UKRAINIAN_CITIES, REGIONS };
